# docker-compose.yml
services:
  db:
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - datadir:/var/lib/mysql
      - ./tests/create_database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3307:3307
    networks:
      - flask-net

  flask:
    container_name: flask
    build: ./
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - flask-net

  web:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
      - db
    ports:
      - "8080:80"
    networks:
      - flask-net

volumes:
  datadir:

networks:
  flask-net:
    name: flask-net