version: '3.8'

# docker-compose.yml
services:
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ktmsx125
      MARIADB_DATABASE: mydb
      MARIADB_USER: niki
      MARIADB_PASSWORD: ktmsx
    volumes:
      - datadir:/var/lib/mysql
      - ./tests/create_database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    networks:
      - flask-net

  flask:
    container_name: flask
    depends_on:
      - db
    build: ./
    ports:
      - 8000:8000
    networks:
      - flask-net
    restart: always

volumes:
  datadir:

networks:
  flask-net:
    name: flask-net