name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    services:
      mariadb:
        image: mariadb:latest
        ports:
            - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ktmsx125
          MYSQL_DATABASE: mydb
          MYSQL_USER: niki
          MYSQL_PASSWORD: ktmsx
          options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
  
    - name: apt update and install python-dev, gcc and libmariadb-dev
      run: |
        sudo apt update
        sudo apt install gcc -y
        sudo apt-get install libmariadb-dev -y
        sudo apt-get install python3.10-dev -y
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m playwright install --with-deps
    - name: Start website
      run: |
        python create_key.py
        python -m flask --app board run --port 8000 --debug &
 
    - name: Run tests
      run: |
        mysql --protocol=tcp -h localhost -P 3306 -uroot -pktmsx125 -e "$(cat $(find ./ -name schema.sql))"
        pytest
